# Important Notes:
# fabric.mod.json's modid field cannot be expanded, you must change it manually.
# Every field you add must be added to the root build.gradle expandProps map.

# FIX BUG, entity locked WAYPOINT SENDS DELETE MESSAGE, doesnt actually remove,
# continues to send delete message, entity still lives. Deletes via command.

# Project
org.gradle.java.home=C:/Program Files/Java/jdk-25.0.4
mod_version=1.8.15-SNAPSHOT
group=com.holybuckets.foundation

# Common
minecraft_version=26.1.2
java_version=25

# Forge
forge_version=64.0.4
forge_loader_version_range=[64,)
forge_version_range=[64,)
minecraft_version_range=[26.1-,26.2)
fabric_minecraft_version_range=~26.1-

# NeoForge
neoforge_version = 26.1.2.21-beta
neoforge_version_range = [26.1,)
neoforge_loader_version_range = [1,)
neo_form_version = 26.1.2-1
parchment_minecraft = 1.21.10
parchment_version = 2025.10.12

# Fabric
fabric_version = 0.146.1+26.1.2
fabric_loader_version = 0.19.2
loom_version=1.14-SNAPSHOT

# Mod options
mod_name=HBs_Foundation
mod_author=Holy_Buckets
mod_id=hbs_foundation
license=MIT
credits=Holy_Buckets
description=HBs Foundation is an API for fundamental methods and utility methods related to all my Minecraft modded projects. Integrated with and dependent on Balm API.

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Dependencies
gson_version=2.8.9
antlr_version=4.9.3
sqlite_version=3.46.1.0
balm_version=26.1.2.5
balm_version_range=[26.1.2.5,)
foundation_version_min=1.7.2

# Publishing
release_dir=C:/Users/jack/Desktop/docs/11_Minecraft/00-Releases